server:
  error:
    include-stacktrace: on_param

spring:
  jpa:
    hibernate:
      ddl-auto: update
#      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#  show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root


